### ISSUE TITLE
RuntimeError while running Bear

### ISSUE THREAD

**Issue by Kostell0** [rail-berkeley/d4rl_evaluations#19]
I tried to run BEAR algorithm with your example command:  `python examples/bear_hdf5_d4rl.py --env='halfcheetah-medium-v0' --policy_lr=1e-4 --num_samples=100`
already at first epoch i am getting this error

RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.FloatTensor [256, 6]], which is output 0 of TBackward, is at version 2; expected version 1 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).

I tried to fix it, but i couldn't. But i realized that with mode != auto it works, but i need mode turned on. But results not so good as expected!

**Comment by zhaoyingnan179346** [comment]
Have you solved this problem? I have met the same problem.
